name: Release

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
    
jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

  build-release:
    needs: checkout
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
          
      - name: Build
        run: |
          mvn package
          echo "artifact_name=$(ls ${{github.workspace}}/target | grep jar)" >> $GITHUB_ENV
          echo "release_version=$(ls ${{github.workspace}}/target | grep jar | egrep -o '[[:digit:]].[[:digit:]].[[:digit:]]' -o)" >> $GITHUB_ENV

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          
  deploy-to-QA-UA:
    needs: build-release
    runs-on: ubuntu-latest
    environment: 'PRO'

    steps:
      - name: deploy-to-QA-UA
        run: echo Deploy to QA-UA    
        
  tests:
    needs: deploy-to-QA-UA
    runs-on: ubuntu-latest

    steps:
      - name: tests
        run: echo Running tests    
        
  post:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: post
        run: echo Running post actions
