name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy (vX.Y.Z)'
        required: true
        default: ''
      environment:
        description: 'Environment to deploy version (DEV/QA/UA/PRO)'
        required: true
        default: ''

jobs:
      
  checkout:
    runs-on: ubuntu-latest

    steps:
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/:repository/releases/latest
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - run: echo "Latest release "${{ steps.get_latest_release.outputs.data | jq '.[].id' }}""
      #- run: "echo latest release: ${{ steps.get_latest_release.outputs.data }}"
      
      - uses: actions/checkout@v2
        with:
          ref: refs/tags/${{ github.event.inputs.version }}
      
  pull-from-Quay:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - run: echo "Pull ${{ github.event.inputs.version }}!"
      
  deploy:
    environment: ${{ github.event.inputs.environment }}
    needs: pull-from-Quay
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/tags/${{ github.event.inputs.version }}
      - run: echo "Deploy to ${{ github.event.inputs.environment }}!"
      
  post:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: post
        run: echo Running post actions
