name: Feature to DEV

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Feature branch to deploy (e.g. feature/TICKET-1234)'
        required: true
        default: ''

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

  build:
    needs: checkout
    runs-on: ubuntu-latest

    steps:
      - run: echo "build"

  deploy-to-DEV:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy to DEV"

  post:
    needs: deploy-to-DEV
    runs-on: ubuntu-latest

    steps:
      - name: post
        run: echo Running post actions
