name: Pull-request checks

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checks
        run: echo "Checks"
